### PR TITLE
Try running script from working directory

### LINKED ISSUE #234: panic trying to run script, when script is given with just a filename
`cargo-bisect-rustc --script timeout.sh`

panics after the first download:

```
checking nightly-2022-10-26 from the currently installed default nightly toolchain as the last failure
checking the start range to find a passing nightly
installing nightly-2022-10-26
testing...
thread 'main' panicked at 'thiserror::Errored to run "timeout.sh": Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/jruderman/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-bisect-rustc-0.6.4/src/toolchains.rs:302:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It should either work, or give an error message earlier saying I need to add the `./` prefix.

(The name and contents of the script don't matter for this bug; an empty script or one with just a shebang line is enough to trigger it.)

### Contrast: actually missing script

`cargo-bisect-rustc --script notfound.sh`

gives a reasonable, early error message:

`error: Invalid value "notfound.sh" for '--script <SCRIPT>': No such file or directory (os error 2)`

### Contrast: prefix script name with `./`

`cargo-bisect-rustc --script ./timeout.sh`

works.

### PR DESCRIPTION
**Pull request by clubby789**
Fixes #234 
If we have a non-absolute path that doesn't begin with `./`, check for the script in the current directory and adjust the script path if it exists.

### CODE REVIEW

File: src/toolchains.rs [hunk 1]
```diff
@@ -238,8 +238,19 @@ impl Toolchain {
...
+        if let Some(path) = &script {
+            if !path.is_absolute() && !path.starts_with("./") && !path.starts_with(".\\") {
+                if let Ok(mut dir) = std::env::current_dir() {
+                    dir.push(path);
+                    if dir.is_file() {
+                        script = Some(dir)
+                    }
+                }
+            }
+        }
```
Comment (ehuss) [inline src/toolchains.rs:251]: I think this could be simplified to something like:

```rust
let script = cfg.args.script.as_ref().map(|script| {
    std::env::current_dir().unwrap().join(script)
});
```

If the path is absolute, it will replace the current dir. Otherwise, it will be joined with it.

**Review by ehuss — COMMENTED** [review]
Thanks for the PR!  I'd love to get this fixed, as I often find it awkward to need `./`.

**Review by ehuss — APPROVED** [review]
Thanks!

I suppose this will break if someone passes an executable from PATH, but I imagine 99% of the time that isn't the case. If that's an issue, we can revert or adjust as needed.
