### PR TITLE
Make `cargo-bisect-rustc` work with hyphen or space

### LINKED ISSUE #359: Unexpected arguments are incorrectly identified
Something about how the command-line arguments are being parsed with Clap makes worse errors than other Cargo subcommand usages of Clap.

This error confusingly says that `bisect-rustc` is unexpected, not that `--components` is unexpected. (The correct flag is called `--component` and Clap should know to suggest this.)

```console
$ cargo bisect-rustc --components=clippy
error: unexpected argument 'bisect-rustc' found

Usage: cargo bisect-rustc [OPTIONS] [-- <COMMAND_ARGS>...]

For more information, try '--help'.
```

Compared to these, which both correctly identify `--components` as unexpected.

```console
$ cargo expand --components=clippy
error: unexpected argument '--components' found

  tip: to pass '--components' as a value, use '-- --components'

Usage: cargo expand [OPTIONS] [ITEM]

For more information, try '--help'.
```

```console
$ cargo docs-rs --components=clippy
error: unexpected argument '--components' found

  tip: a similar argument exists: '--open'

Usage: cargo docs-rs <--open|--verbose|--color <WHEN>|--version|--package <SPEC>|--jobs <N>|--target <TARGET>|--target-dir <DIRECTORY>|--manifest-path <PATH>|--frozen|--locked|--offline>

For more information, try '--help'.
```

### PR DESCRIPTION
**Pull request by ehuss**
This makes it so that the executable name `cargo-bisect-rustc` (with a hyphen) works the same as `cargo bisect-rustc` (with a space). This fixes parsing problems when used with a space as demonstrated in #359.

Previously, cbr would try to support both forms, but it didn't always work (see #359). This is due to the way it was trying to do a fallback parsing without the subcommand, which means CLI parsing errors when used as a subcommand to not work (since the original error was discarded).

The solution is to not attempt to use clap to do subcommand handling, and instead just strip the `bisect-rustc` subcommand if it exists.

Other than fixing the errors, one observable change is that `cargo-bisect-rustc` (without a space, with no arguments) will now behave the same as `cargo bisect-rustc` (it will start the bisection process). Previously it would print a somewhat confusing error about the missing `bisect-rustc` subcommand. This also apples to `--help` and `-h`.

Fixes #359

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -397,16 +391,15 @@ impl Config {
...
-            }
-            _ => Opts::parse(),
-        },
-    };
+    let mut os_args: Vec<_> = std::env::args_os().collect();
+    // This allows both `cargo-bisect-rustc` (with a hyphen) and
+    // `cargo bisect-rustc` (with a space) to work identically.
+    if let Some(command) = os_args.get(1) {
+        if command == "bisect-rustc" {
+            os_args.remove(1);
```
Comment (oli-obk) [inline src/main.rs:399]: Weird that we don't need to adjust arg 0 to show "the right" (whatever that means) command. The output seems to look right

**Review by oli-obk — APPROVED** [review]
